services:
  db:
    image: pgvector/pgvector:pg16
    container_name: sin_ruido_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sin_ruido
    ports:
      - "5432:5432"
    volumes:
      - sin_ruido_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d sin_ruido"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sin_ruido_pgdata:
