// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A quien avisa el motor cuando algo se rompe.
 *
 * **`ultima_prueba_ok` es el campo que da sentido a todo esto.** Un destino
 * configurado no dice nada: la casilla que se usaba para probar la deshabilito
 * su proveedor y el motor siguio intentando meses contra una direccion muerta
 * -- un envio fallido solo deja un `logger.error` que nadie mira. Esta fecha es
 * lo unico que distingue "hay un mail puesto" de "el mail sale".
 */
export type Alertas = { 
/**
 * Las direcciones. Vacia es un estado valido y significa "no avisar por
 * mail": el motor cae al log, que sigue siendo un canal.
 */
destinos: Array<string>, configurado: boolean, 
/**
 * Si el motor tiene un servidor de correo configurado. **Es un booleano y
 * nunca el host ni la cuenta**, misma regla que `secreto_configurado`: la
 * cabina necesita saber si el canal puede funcionar, no con que credencial.
 */
smtp_configurado: boolean, actualizado_en: string | null, 
/**
 * Cuando salio un mail de prueba por ultima vez. `null` = nunca se probo.
 */
ultima_prueba_ok: string | null, };
