// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoticiaBreve } from "./NoticiaBreve";

export type Cluster = { id: number, titulo_evento: string, 
/**
 * `abierto` | `procesado` | `descartado`. Se deja como texto y no como
 * enum: el motor lo guarda como string libre en la columna, así que un
 * enum cerrado acá inventaría una garantía que la base no da.
 */
estado: string, fecha_creacion: string, cantidad_noticias: number, 
/**
 * Cuántas síntesis tiene el cluster. **Sin `Option`**: el motor lo
 * devuelve siempre, con `0` cuando no hay ninguna, justamente para que la
 * ventana no tenga que distinguir "no tiene" de "no vino el campo".
 *
 * Este campo forma parte del contrato con el motor
 * (`tests/test_contrato_api.py`), así que tocarlo hace correr las dos
 * CI: la de la app por el archivo, y la del motor por el binding que se
 * regenera.
 *
 * Existe porque sin él la lista de trabajo tenía que paginar
 * `GET /sintesis` entera para saber qué cluster ya estaba resuelto.
 * Medido el 07/09/2026 desde esta misma app: 5 páginas y 201 ms antes de
 * dibujar una fila, creciendo a ~28 síntesis por día.
 */
cantidad_sintesis: number, medios: Array<string>, noticias: Array<NoticiaBreve>, };
