// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoticiaBreve } from "./NoticiaBreve";

export type Cluster = { id: number, titulo_evento: string, 
/**
 * `abierto` | `procesado` | `descartado`. Se deja como texto y no como
 * enum: el motor lo guarda como string libre en la columna, así que un
 * enum cerrado acá inventaría una garantía que la base no da.
 */
estado: string, fecha_creacion: string, cantidad_noticias: number, medios: Array<string>, noticias: Array<NoticiaBreve>, };
