// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Corrida = { id: number, inicio: string, 
/**
 * Los tres son `None` juntos mientras la corrida no cerró. No es un caso
 * hipotético: está capturado en `pipeline.json`, en `anteriores[0]`.
 */
fin: string | null, duracion_segundos: number | null, utilizacion: number | null, 
/**
 * **Un mapa y no un struct.** Las claves las decide `_correr_paso` en
 * tiempo de ejecución y van en español con acentos y espacios
 * (`síntesis`, `purga de cuerpos`, `entrega al backend`), así que fijarlas
 * acá sería atarse a que nadie agregue un paso nunca.
 *
 * El tipo de TypeScript va escrito a mano y no derivado: sin esto, `ts-rs`
 * genera un módulo `serde_json/JsonValue` **fuera de `src/bindings/`**,
 * que es el único directorio que el guardián `bindings:check` vigila.
 */
pasos: Record<string, unknown>, };
