// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnfoqueDeMedio } from "./EnfoqueDeMedio";
import type { Fuente } from "./Fuente";

/**
 * Una síntesis entera.
 *
 * El motor la arma como `{**_resumen_de_sintesis(s), ...}`, así que acá es un
 * `flatten` sobre el resumen y no una copia de sus diez campos. Copiarlos
 * habría dejado dos definiciones del mismo dato que hay que cambiar juntas.
 */
export type DetalleSintesis = { 
/**
 * `None` si la síntesis quedó sin cluster: `detalle_de_sintesis` lo emite
 * con una guarda explícita.
 */
titulo_evento: string | null, resumen_neutro: string, puntos_clave: Array<string>, 
/**
 * **Indexada por nombre de medio**, no una lista con un campo `medio`.
 * Es lo primero que la captura corrigió: un `Vec<_>` no deserializa esto.
 */
comparativa_enfoques: { [key in string]: EnfoqueDeMedio }, fuentes: Array<Fuente>, id: number, cluster_id: number, titulo_angulo: string, topicos: Array<string>, subtopicos: Array<string>, medios: Array<string>, cantidad_notas: number, fecha_generacion: string, 
/**
 * `Sintesis.modelo_usado` es nullable en el modelo. El fixture lo trae
 * lleno; el modelo manda.
 */
modelo_usado: string | null, enviado_backend: boolean, };
