// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cómo cubrió un medio el evento.
 *
 * Las tres claves están siempre: no vienen del modelo tal cual, las arma
 * `_validar_enfoques` construyendo el diccionario campo por campo.
 */
export type EnfoqueDeMedio = { destaco: string, omitio: string, 
/**
 * Frase textual del cuerpo que respalda lo anterior.
 */
cita: string, };
