// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A donde el motor entrega las sintesis.
 *
 * **Aca si viaja la URL**, a diferencia de `Salud`: estas dos rutas exigen
 * token siempre -- incluso en un despliegue con la API abierta -- y el operador
 * no puede corregir un destino que no ve. Lo que no viaja nunca es el secreto
 * compartido; de el solo se informa si existe.
 */
export type Entrega = { 
/**
 * `null` cuando no hay destino: la entrega no corre y las sintesis se
 * acumulan entregables.
 */
url: string | null, 
/**
 * Hay una URL guardada.
 */
configurado: boolean, 
/**
 * El motor la va a aceptar cuando entregue. **No es lo mismo que
 * `configurado`**: la fila puede venir sembrada por la migracion desde un
 * `.env` viejo, o editada a mano en la base. Sin este campo el operador
 * veia "configurado" mientras el barrido la descartaba en silencio.
 */
valido: boolean, 
/**
 * Por que no sirve, con el mensaje del validador. `null` si sirve.
 */
problema: string | null, 
/**
 * Si `WEBHOOK_SECRET` esta seteado en el entorno del motor. Sin el la
 * entrega no corre aunque haya destino, asi que es lo que explica un
 * "configurado pero no entrega".
 */
secreto_configurado: boolean, actualizado_en: string | null, };
