// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Por qué no se pudo manejar el motor, en categorías cerradas.
 *
 * **La diferencia entre `NoInstalado` y `DemonioCaido` es la que importa**:
 * piden acciones distintas de quien mira —instalar algo contra prender algo—
 * y sin separarlas la app solo puede mostrar el texto crudo de Docker, que
 * dice qué pasó pero no qué hacer.
 */
export type ErrorDocker = { "tipo": "no_instalado" } | { "tipo": "demonio_caido" } | { "tipo": "fallo", "detalle": string };
