// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Por qué falló un pedido, en categorías cerradas.
 *
 * **No es un `String` con el error crudo**, y es la misma decisión que el
 * motor tomó para su campo `agotados` después de que un mensaje de error
 * filtrara el nombre de una variable de entorno: lo que cruza una frontera
 * viaja como categoría, y el detalle se queda de este lado.
 */
export type ErrorDeApi = { "tipo": "sin_token" } | { "tipo": "motor_caido" } | { "tipo": "no_autorizado" } | { "tipo": "no_encontrado" } | { "tipo": "invalida", "detalle": string } | { "tipo": "no_disponible", "detalle": string } | { "tipo": "respuesta", "detalle": number } | { "tipo": "red", "detalle": string };
