// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * En qué anda el motor, tal como lo ve la interfaz.
 */
export type Estado = "parado" | "reconstruyendo" | "arrancando" | "migrando" | "listo" | "error";
