// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Algo que el motor considero digno de avisar.
 *
 * **Una fila por clave con contador, no una por ocurrencia.** Un feed caido
 * toda la noche daria 96 filas identicas que tapan todo lo demas -- el mismo
 * problema que el cooldown evita en el mail. Y la fila se escribe **aunque el
 * cooldown silencie el envio**: son dos consumidores del mismo hecho con
 * necesidades opuestas.
 */
export type EventoRegistrado = { id: number, 
/**
 * La clave con la que el motor agrupa el aviso: `ingesta:La Nacion`.
 */
clave: string, 
/**
 * Lo que va antes del `:`. Viene derivada del motor para poder filtrar sin
 * partir la clave de este lado.
 */
categoria: string, asunto: string, mensaje: string, 
/**
 * Cuantas veces ocurrio. **Es el numero que distingue un tropiezo de algo
 * roto**, y el que se perderia si el evento se registrara solo cuando el
 * mail sale.
 */
veces: number, 
/**
 * Desde cuando viene pasando. No se pisa al repetirse.
 */
primera_vez: string, ultima_vez: string, 
/**
 * Si informa algo que ya no se puede deshacer -- una sintesis abandonada,
 * por ejemplo. Sale de los avisos que pasan `ignorar_cooldown`, asi que la
 * severidad no necesito un campo propio.
 */
terminal: boolean, };
