// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Qué encontró el motor del otro lado de **un** feed.
 */
export type FeedSondeado = { url: string, items: number, 
/**
 * Cuántos de esos items traen el cuerpo en el feed. Si es cero, el medio
 * publica titulares y el cuerpo hay que ir a buscarlo a la página.
 */
con_cuerpo: number, 
/**
 * Qué ventana de tiempo cubre lo que trajo. Muy grande huele a archivo y
 * no a feed vivo.
 */
ventana_horas: number | null, };
