// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TopicoDeSolos } from "./TopicoDeSolos";

/**
 * Con quién se junta un medio, y cuándo no.
 */
export type FilaDelPanel = { medio_id: number, nombre: string, activo: boolean, clusters: number, 
/**
 * En cuántos clusters es el **único** medio. Eso no se sintetiza nunca:
 * material que se produce y no se publica.
 */
solo: number, con_el_minimo: number, sobre_el_minimo: number, 
/**
 * Ordenado de mayor a menor. Es para leer de arriba hacia abajo.
 */
topicos_cuando_esta_solo: Array<TopicoDeSolos>, 
/**
 * Los que no tienen sección derivable de la URL. Van aparte y **no** en un
 * "otros", que los escondería adentro de un número.
 */
sin_topico_cuando_esta_solo: number, };
