// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Fuente = { id: number, 
/**
 * Acá sí es opcional: `detalle_de_sintesis` lo emite como
 * `n.medio.nombre if n.medio else None`.
 */
medio: string | null, titulo: string, url: string, fecha_publicacion: string, };
