// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Un medio del roster.
 *
 * **Acá no hay nada que filtrar**, a diferencia de `ModeloPublico`: un medio no
 * guarda credenciales, sólo datos que el propio medio publica de sí mismo.
 */
export type MedioPublico = { id: number, nombre: string, url_base: string, feeds_rss: Array<string>, activo: boolean, idioma: string, pais: string | null, logo_url: string | null, 
/**
 * Si el motor va a buscar a la página el cuerpo que el medio **eligió no
 * publicar** en su feed. Se muestra pero no se edita desde acá: es una
 * decisión aparte del operador, no un dato del medio.
 */
extraer_por_url: boolean, };
