// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Un modelo, **con los campos que la app usa y no más**.
 *
 * La excepción documentada a la estrictez del módulo, y tiene un motivo
 * concreto: `_vista_publica` devuelve `modelo.model_dump(exclude={...})`, o
 * sea que esta respuesta **es la tabla** menos dos columnas. Pedir todos sus
 * campos ataría la app a que nadie agregue una columna nunca — un cambio que
 * del lado del motor no se piensa como cambio de API.
 *
 * Lo que queda afuera a propósito: `temperatura`, `max_tokens`,
 * `modo_estructura` y `opciones`. Son cómo se llama al proveedor, no algo que
 * la ventana muestre o decida.
 */
export type ModeloPublico = { id: number, nombre: string, modelo: string, adaptador: string, activo: boolean, prioridad: number, 
/**
 * Si la variable de entorno con la credencial está seteada. **No dice
 * cuál es**: el nombre de la variable no sale del motor desde que un
 * mensaje de error lo filtró.
 */
credencial_configurada: boolean, };
