// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Por qué el motor no llamó al proveedor. Categoría cerrada del lado del
 * motor también — ver el docstring de `synthesize_cluster`.
 */
export type Motivo = "sin_medios_suficientes" | "sin_material_nuevo";
