// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoticiaBreve = { id: number, titulo: string, url: string, 
/**
 * Sin `Option`, al revés que en `Fuente`: `listar_clusters` accede a
 * `n.medio.nombre` sin guarda, así que si fuera `None` el motor devolvería
 * un 500 y nunca llegaría un `null` hasta acá.
 */
medio: string, };
