// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetalleSintesis } from "./DetalleSintesis";

export type RespuestaDetalle = { status: string, sintesis: DetalleSintesis, };
