// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MedioPublico } from "./MedioPublico";

export type RespuestaMedios = { status: string, activos: number, total: number, medios: Array<MedioPublico>, };
