// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResumenSintesis } from "./ResumenSintesis";

export type RespuestaSintesis = { status: string, cantidad: number, sintesis: Array<ResumenSintesis>, 
/**
 * El cursor de la página siguiente. `None` es el final de la lista, no un
 * error: se manda tal cual vino en el próximo pedido.
 */
siguiente: string | null, };
