// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventoRegistrado } from "./EventoRegistrado";

export type RespuestaEventos = { status: string, 
/**
 * Las categorias que existen **de verdad**, para armar el filtro con eso y
 * no con una lista fija que se desactualiza cuando el motor suma un aviso.
 */
categorias: Array<string>, eventos: Array<EventoRegistrado>, };
