// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Corrida } from "./Corrida";

export type RespuestaPipeline = { status: string, corriendo: boolean, 
/**
 * Una corrida que quedó abierta de un proceso que murió. Se informa
 * aparte en vez de mentir `corriendo: true` para siempre.
 */
huerfana: boolean, intervalo_minutos: number, 
/**
 * `None` en un motor recién instalado, que todavía no corrió nunca.
 */
ultima: Corrida | null, anteriores: Array<Corrida>, };
