// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lo que devuelve prender o apagar un modelo.
 *
 * **`modelo` es el nombre y no un objeto**, a diferencia del alta. No es un
 * descuido del motor: los dos endpoints contestan cosas distintas porque
 * responden preguntas distintas -- el alta devuelve la fila que acaba de
 * crear, y el PATCH devuelve con que quedo trabajando el motor.
 */
export type RespuestaActivarModelo = { status: string, 
/**
 * El nombre del modelo que se toco.
 */
modelo: string, activo: boolean, 
/**
 * Con cual esta sintetizando el motor **ahora**, que no siempre es el que
 * se acaba de tocar: prender uno apaga a los demas, y apagar el ultimo deja
 * al motor sin sintetizar.
 */
en_uso: string, };
