// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MedioPublico } from "./MedioPublico";
import type { Sondeo } from "./Sondeo";

/**
 * Lo que devuelven el alta y la edición de un medio.
 */
export type RespuestaMedio = { status: string, medio: MedioPublico, 
/**
 * `None` cuando no hubo sondeo. Pasa al editar sólo el nombre: corregir un
 * tipeo no puede fallar porque el servidor del medio esté caído.
 */
sondeo: Sondeo | null, 
/**
 * Lo que el operador debería mirar y **no** impide guardar: un feed sin
 * cuerpo, un robots restrictivo, una ventana que parece archivo.
 */
avisos: Array<string>, };
