// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilaDelPanel } from "./FilaDelPanel";
import type { TotalesDeClusters } from "./TotalesDeClusters";

/**
 * El panel de composición: qué medio conviene sumar.
 */
export type RespuestaPanel = { status: string, 
/**
 * Cuántos medios distintos necesita un cluster para sintetizarse.
 *
 * **Viaja en vez de estar escrito en la ventana.** La pantalla dice "esto
 * no se puede sintetizar" sobre la columna `solo`, y esa frase sólo es
 * cierta si el balde se calculó contra este número. Si el motor lo cambia,
 * la etiqueta sigue siendo verdad sin tocar la interfaz.
 */
minimo_para_sintetizar: number, clusters: TotalesDeClusters, medios: Array<FilaDelPanel>, };
