// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cluster } from "./Cluster";

export type RespuestaClusters = { status: string, cantidad: number, clusters: Array<Cluster>, };
