// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeloPublico } from "./ModeloPublico";

export type RespuestaModelos = { status: string, 
/**
 * Nunca es `null`: `_nombre_en_uso` devuelve un centinela cuando no hay
 * ninguno activo, justamente para no obligar a distinguir dos formas de
 * decir lo mismo.
 */
en_uso: string, modelos: Array<ModeloPublico>, };
