// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeloPublico } from "./ModeloPublico";

/**
 * Lo que devuelve dar de alta un modelo.
 */
export type RespuestaAltaModelo = { status: string, modelo: ModeloPublico, en_uso: string, };
