// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResumenSintesis = { id: number, cluster_id: number, titulo_angulo: string, topicos: Array<string>, subtopicos: Array<string>, medios: Array<string>, cantidad_notas: number, fecha_generacion: string, 
/**
 * `Sintesis.modelo_usado` es nullable en el modelo. El fixture lo trae
 * lleno; el modelo manda.
 */
modelo_usado: string | null, enviado_backend: boolean, };
