// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Qué dice el `robots.txt` del medio.
 *
 * **Es criterio del operador y no un bloqueo**, y por eso viaja: el motor deja
 * dar de alta un medio con robots restrictivo, pero quien decide tiene que
 * poder verlo antes de decidir.
 */
export type RobotsSondeado = { legible: boolean, 
/**
 * **Nulo cuando el `robots.txt` no se pudo leer**: ahi no se sabe si
 * permite o no, y `false` seria afirmar algo que nadie comprobo.
 */
permite_extraer: boolean | null, 
/**
 * Por que no se pudo leer. **Nulo cuando si se pudo**, que es el caso
 * normal: no hay nada que explicar.
 */
detalle: string | null, };
