// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Qué dice el `robots.txt` del medio.
 *
 * **Es criterio del operador y no un bloqueo**, y por eso viaja: el motor deja
 * dar de alta un medio con robots restrictivo, pero quien decide tiene que
 * poder verlo antes de decidir.
 */
export type RobotsSondeado = { legible: boolean, permite_extraer: boolean, detalle: string, };
