// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Salud = { status: string, database: string, environment: string, hora_local: string, 
/**
 * La version del motor que esta corriendo.
 *
 * **Motor y ventana se numeran juntos desde la 1.2.0.** No son dos
 * productos: la cabina no aplica sobre ninguna otra cosa que el motor, asi
 * que una version nueva incluye a los dos. Este campo es con lo que la
 * ventana comprueba que el par no derivo -- un par desparejo no se rompe,
 * se comporta raro, y eso es peor que un error.
 */
version: string, 
/**
 * Si el motor exige `Authorization` en el resto de sus endpoints.
 *
 * `API_TOKEN` es opcional del lado del motor: sin definir, la API queda
 * abierta. Sin este campo la cabina pedía un token igual, y quien
 * instalara contra un motor abierto tenía que inventar uno para pasar de
 * la primera pantalla.
 */
exige_token: boolean, 
/**
 * Si hay un destino de entrega configurado.
 *
 * **Es un booleano y el motor no manda la URL por acá**: `GET /` es una
 * ruta abierta. Sirve para no marcar síntesis como "sin entregar" cuando
 * no hay a dónde entregarlas — sin él, 119 de 507 mentían.
 */
entrega_configurada: boolean, };
