// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Salud = { status: string, database: string, environment: string, hora_local: string, };
