// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Motivo } from "./Motivo";

/**
 * Lo que cruza a la ventana.
 *
 * **Es un enum etiquetado y no la respuesta cruda**, por lo mismo que
 * `ErrorDeApi`: un `200` que a veces significa "no hice nada" obliga a quien
 * dibuja a leer un booleano y después adivinar qué otros campos vinieron. Con
 * la etiqueta, TypeScript lo discrimina y el `switch` queda exhaustivo.
 */
export type Sintetizado = { "tipo": "hecha", cluster_id: number, creados: number, actualizados: number, descartados: number, } | { "tipo": "cortada", cluster_id: number, motivo: Motivo, };
