// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedSondeado } from "./FeedSondeado";
import type { RobotsSondeado } from "./RobotsSondeado";

/**
 * El informe del sondeo: lo que hay del otro lado, antes de guardar nada.
 *
 * **Es lo que convierte el alta en una decisión.** Sin esto, dar de alta un
 * medio es "registrá esto"; con esto es "esto es lo que encontramos, decidí".
 */
export type Sondeo = { items_totales: number, items_con_cuerpo: number, feeds: Array<FeedSondeado>, robots: RobotsSondeado, };
