// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De qué tema son los clusters donde un medio quedó solo.
 */
export type TopicoDeSolos = { topico: string, clusters: number, };
