// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TotalesDeClusters = { total: number, solo: number, con_el_minimo: number, sobre_el_minimo: number, };
