"""modelo_ia configurable y modelo_usado en sintesis

Revision ID: 0ddec0462447
Revises: b4f1a9d27c30
Create Date: 2026-08-20 20:32:50.690415

Backlog punto 2: que el operador elija con qué modelo sintetiza sin editar
código. Ver specs/roadmap.md y src/models/modelo_ia.py.

**No cambia el comportamiento de una base existente.** La tabla nace vacía, y
sin filas activas la síntesis sigue yendo por el camino histórico de Gemini.

`modelo_usado` queda nullable a propósito: las síntesis anteriores a esta
migración no tienen forma de saber con qué modelo se generaron, y ponerles el
actual sería inventar un dato.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Necesarios para los tipos propios de los modelos: sqlmodel.sql.sqltypes.AutoString
# y pgvector.sqlalchemy.Vector aparecen en las migraciones autogeneradas.
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0ddec0462447'
down_revision: Union[str, Sequence[str], None] = 'b4f1a9d27c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adaptador', sa.Enum('OPENAI_COMPATIBLE', 'GEMINI', 'ANTHROPIC', name='adaptador'), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key_env', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modo_estructura', sa.Enum('RESPONSE_FORMAT', 'TOOLS', name='modoestructura'), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    # Nullable a propósito: `None` significa "sin techo de tokens", que es el
    # default. Ver el comentario en `models/modelo_ia.py`.
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelo_ia_activo'), 'modelo_ia', ['activo'], unique=False)
    op.create_index(op.f('ix_modelo_ia_nombre'), 'modelo_ia', ['nombre'], unique=True)
    op.add_column('sintesis', sa.Column('modelo_usado', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_sintesis_modelo_usado'), 'sintesis', ['modelo_usado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_sintesis_modelo_usado'), table_name='sintesis')
    op.drop_column('sintesis', 'modelo_usado')
    op.drop_index(op.f('ix_modelo_ia_nombre'), table_name='modelo_ia')
    op.drop_index(op.f('ix_modelo_ia_activo'), table_name='modelo_ia')
    op.drop_table('modelo_ia')

    # Agregado a mano: `drop_table` NO borra los tipos ENUM que `sa.Enum` creó
    # en PostgreSQL, así que quedarían huérfanos y el `upgrade` siguiente
    # fallaría con "type already exists". Es el agujero clásico de las
    # migraciones autogeneradas con enums, y un downgrade que no se puede
    # deshacer no sirve para nada.
    sa.Enum(name='modoestructura').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='adaptador').drop(op.get_bind(), checkfirst=True)
