"""Esquema inicial: medio, noticia, cluster, sintesis

Revision ID: 5d06f53f689a
Revises: 
Create Date: 2026-08-07 22:27:25.605932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Necesarios para los tipos propios de los modelos: sqlmodel.sql.sqltypes.AutoString
# y pgvector.sqlalchemy.Vector aparecen en las migraciones autogeneradas.
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d06f53f689a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo_evento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_estado'), 'cluster', ['estado'], unique=False)
    op.create_index(op.f('ix_cluster_titulo_evento'), 'cluster', ['titulo_evento'], unique=False)
    op.create_table('medio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_base', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feed_rss', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medio_nombre'), 'medio', ['nombre'], unique=False)
    op.create_table('noticia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medio_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('contenido_limpio', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['medio_id'], ['medio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noticia_cluster_id'), 'noticia', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_noticia_fecha_publicacion'), 'noticia', ['fecha_publicacion'], unique=False)
    op.create_index(op.f('ix_noticia_guid'), 'noticia', ['guid'], unique=True)
    op.create_index(op.f('ix_noticia_medio_id'), 'noticia', ['medio_id'], unique=False)
    op.create_index(op.f('ix_noticia_url'), 'noticia', ['url'], unique=True)
    op.create_table('sintesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('resumen_neutro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('puntos_clave', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('comparativa_enfoques', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sintesis_cluster_id'), 'sintesis', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sintesis_cluster_id'), table_name='sintesis')
    op.drop_table('sintesis')
    op.drop_index(op.f('ix_noticia_url'), table_name='noticia')
    op.drop_index(op.f('ix_noticia_medio_id'), table_name='noticia')
    op.drop_index(op.f('ix_noticia_guid'), table_name='noticia')
    op.drop_index(op.f('ix_noticia_fecha_publicacion'), table_name='noticia')
    op.drop_index(op.f('ix_noticia_cluster_id'), table_name='noticia')
    op.drop_table('noticia')
    op.drop_index(op.f('ix_medio_nombre'), table_name='medio')
    op.drop_table('medio')
    op.drop_index(op.f('ix_cluster_titulo_evento'), table_name='cluster')
    op.drop_index(op.f('ix_cluster_estado'), table_name='cluster')
    op.drop_table('cluster')
    # ### end Alembic commands ###
