"""Cluster: medios al momento de la ultima sintesis

Revision ID: 98c48e2dc7b1
Revises: 979689aeb928
Create Date: 2026-08-08 20:54:13.945839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Necesarios para los tipos propios de los modelos: sqlmodel.sql.sqltypes.AutoString
# y pgvector.sqlalchemy.Vector aparecen en las migraciones autogeneradas.
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '98c48e2dc7b1'
down_revision: Union[str, Sequence[str], None] = '979689aeb928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('medios_al_sintetizar', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'medios_al_sintetizar')
    # ### end Alembic commands ###
