"""tabla de corridas del pipeline

Revision ID: b963fe84825f
Revises: 5a246beb14bd
Create Date: 2026-09-06 15:35:35.088954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Necesarios para los tipos propios de los modelos: sqlmodel.sql.sqltypes.AutoString
# y pgvector.sqlalchemy.Vector aparecen en las migraciones autogeneradas.
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b963fe84825f'
down_revision: Union[str, Sequence[str], None] = '5a246beb14bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_segundos', sa.Float(), nullable=True),
    sa.Column('utilizacion', sa.Float(), nullable=True),
    sa.Column('pasos', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrida_inicio'), 'corrida', ['inicio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corrida_inicio'), table_name='corrida')
    op.drop_table('corrida')
    # ### end Alembic commands ###
