"""topico y topico_secundario en sintesis

De qué tema es cada publicación, para que el back-end pueda armar secciones y
filtros. Los valores salen de la lista cerrada de `services/topicos.py`.

Nulables, y sin `server_default`: las síntesis que ya existen se generaron antes
de que el campo existiera y no hay con qué completarlas sin volver a llamar al
modelo. Un hueco explícito es más honesto que un default inventado.

Revision ID: eb625bff05fc
Revises: faa5d6fc466e
Create Date: 2026-08-09 19:40:13.308592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Necesarios para los tipos propios de los modelos: sqlmodel.sql.sqltypes.AutoString
# y pgvector.sqlalchemy.Vector aparecen en las migraciones autogeneradas.
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'eb625bff05fc'
down_revision: Union[str, Sequence[str], None] = 'faa5d6fc466e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sintesis', sa.Column('topico', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sintesis', sa.Column('topico_secundario', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_sintesis_topico'), 'sintesis', ['topico'], unique=False)
    op.create_index(op.f('ix_sintesis_topico_secundario'), 'sintesis', ['topico_secundario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sintesis_topico_secundario'), table_name='sintesis')
    op.drop_index(op.f('ix_sintesis_topico'), table_name='sintesis')
    op.drop_column('sintesis', 'topico_secundario')
    op.drop_column('sintesis', 'topico')
    # ### end Alembic commands ###
